NorthwindWeb/Models/ShopCart/ProductShopCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using NorthwindWeb.Context;

namespace NorthwindWeb.Models.ShopCart
{
    /// <summary>
    /// contain basic info about shopcart
    /// </summary>
    public class ProductShopCart
    {
        /// <summary>
        /// product id from shopcart
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// quantity of product
        /// </summary>
        public int Quantity { get; set; } = 1;
    }

    /// <summary>
    /// ProductShopCartDetailed have aditional information about the product as against ProductShopCart
    /// </summary>
    public class ProductShopCartDetailed : ProductShopCart
    {

        /// <summary>
        /// Get category of this product
        /// </summary>
        public string ProductName
        {
            get
            {
                return (new NorthwindDatabase()).Products.Find(ID).ProductName;
            }
            set
            {

            }
        }

        /// <summary>
        /// get unit price of this product
        /// </summary>
        public decimal UnitPrice
        {
            get
            {
                return (new NorthwindDatabase()).Products.Find(ID).UnitPrice ?? 99999999;
            }
            set
            {

            }
        }

        /// <summary>
        /// get the category of this product
        /// </summary>
        public string Category
        {
            get
            {
                return (new NorthwindDatabase()).Products.Find(ID).Category.CategoryName;
            }
            set
            {

            }
        }

    }
}

NorthwindWeb/Models/ShopCart/ProductShopResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace NorthwindWeb.Models.ShopCart
{
    /// <summary>
    /// Contains the response for shopcart from server
    /// </summary>
    /// <typeparam name="DataType">IQueriable if we have a proper database or string of json from another database</typeparam>
    public class ProductShopResponse<DataType>
    {
        /// <summary>
        /// contains all errors
        /// </summary>
        public enum  ErrorType
        {
            /// <summary>
            /// no error found
            /// </summary>
            NoError,
            /// <summary>
            /// a unknown type of error ocure
            /// </summary>
            UnknownError,
            /// <summary>
            /// order contains some invalid data
            /// </summary>
            InvalidOrder
        }

        /// <summary>
        /// true if server cannot send back a proper response
        /// </summary>
        ErrorType Error { get; set; } = ErrorType.NoError;

        /// <summary>
        /// Title of message
        /// </summary>
        string MessageTitle { get; set; }

        /// <summary>
        /// Message
        /// </summary>
        string MessageText { get; set; }

        /// <summary>
        /// Data about product that will be sent to client
        /// </summary>
        DataType data { get; set; }
    }
}

NorthwindWeb/Models/ShopCarts.cs
namespace NorthwindWeb.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// The entity that holds all the information from the ShopCarts table in the database.
    /// </summary>
    [Table("ShopCarts")]
    public partial class ShopCarts
    {
        /// <summary>
        /// The name of the user who added a product in the shopcart
        /// </summary>
        [Key]
        [StringLength(256)]
        [Column(Order = 1)]
        public string UserName { get; set; }

        /// <summary>
        /// The id of the product added.
        /// </summary>
        [Key]
        [Column(Order = 2)]
        public int ProductID { get; set; }

        /// <summary>
        /// The quantity of the product.
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// The products contained by the shopcart
        /// </summary>
        public virtual Products Products { get; set; }
    }
}

NorthwindWeb/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NorthwindWeb.Models;
using NorthwindWeb.Models.ServerClientCommunication;
using Newtonsoft.Json.Linq;
using NorthwindWeb.Models.ShopCart;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Data;
using NorthwindWeb.ViewModels;
using NorthwindWeb.Context;

namespace NorthwindWeb.Controllers
{
    /// <summary>
    /// Contains all the methods neccessary for interacting with the shopcart.
    /// For example adding/removing products from the shopcart, or creating an order with those products.
    /// </summary>
    public class ShopCartController : Controller, NorthwindWeb.Models.Interfaces.IJsonTableFillServerSide
    {
        NorthwindDatabase db = new NorthwindDatabase();
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(ShopCartController));

        private static Random random = new Random();
        private string CustomerId()
        {
            const string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            string result = new string(Enumerable.Repeat(chars, 5)
              .Select(s => s[random.Next(s.Length)]).ToArray());
            if (db.Customers.Find(result) != null)
                result = CustomerId();
            return result;
        }

        

        /// <summary>
        /// See the curent shop list
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
           
            ViewBag.ShipVia = new SelectList(db.Shippers, "ShipperID", "CompanyName");
            return View();
        }

        /// <summary>
        /// Inserts or updates a product in the ShopCart table.
        /// </summary>
        /// <param name="id">The id of the product</param>
        /// <param name="quantity">The quantity of the product</param>
        [Authorize]
        public string Create(int id, int quantity)
        {
            if (!(db.Products.Where(x => x.ProductID == id).Any()) || db.Products.Where(x => x.ProductID == id).First().Discontinued)
            {
                return "Error";
            }
            try
            {
                if (!(db.ShopCart.Any(x => x.ProductID == id && x.UserName == User.Identity.Name)))
                {
                    ShopCarts cart = new ShopCarts() { UserName = User.Identity.Name, ProductID = id, Quantity = quantity, Products = db.Products.Find(id) };
                    db.ShopCart.Add(cart);
                    db.SaveChanges();
                }
                else
                {
                    Update(id, quantity);
                }
                return "{}";
            }
            catch (Exception e)
            {
                logger.Error(e.ToString());
                return "Error";
            }
        }

        private void Update(int id, int quantity)
        {
            var cart = db.ShopCart.Where(x => x.ProductID == id && x.UserName == User.Identity.Name).FirstOrDefault();
            //todo anunta clientul ca nu sunt suficiente unitati in stock
            //short? unitsInStock = db.Products.Find(cart.ProductID).UnitsInStock ?? 0;
            cart.Quantity = cart.Quantity >= short.MaxValue ? short.MaxValue : cart.Quantity + quantity;
            db.SaveChanges();
        }

        /// <summary>
        /// Updates the quantity of a product in the database. The product must exist.
        /// </summary>
        /// <param name="id">The id of the product.</param>
        /// <param name="quantity">The new quantity value.</param>
        /// <returns>"{}" on success, "Error" on failure.</returns>
        public string UpdateQuantity(int id, int quantity)
        {
            if (quantity <= 0 || quantity >= short.MaxValue || !(db.ShopCart.Any(x => x.ProductID == id && x.UserName == User.Identity.Name)))
            {
                return "Error";
            }

            db.ShopCart.Where(x => x.ProductID == id && x.UserName == User.Identity.Name).First().Quantity = quantity;
            db.SaveChanges();
            return "{}";//for ajax this means success
        }

        /// <summary>
        /// Import data from local storage when the user will log in.
        /// </summary>
        /// <param name="json">data will be parsed as a json string</param>
        /// <returns>"{}" on success, "Error" on fail</returns>
        public string ImportFromLocal(string json = "")
        {
            var shopCartProducts = JsonConvert.DeserializeObject<List<ProductShopCart>>(json).AsQueryable();
            try
            {
                if (User.Identity.IsAuthenticated && shopCartProducts.Count() != 0)
                {
                    foreach (var shopCartProduct in shopCartProducts)
                    {
                        if (!(db.Products.Any(x => x.ProductID == shopCartProduct.ID)) || db.Products.Where(x => x.ProductID == shopCartProduct.ID).First().Discontinued)
                        {
                            continue;
                        }
                        if (db.ShopCart.Any(x => x.UserName == User.Identity.Name && x.ProductID == shopCartProduct.ID))
                        {
                            db.ShopCart.Where(x => x.UserName == User.Identity.Name && x.ProductID == shopCartProduct.ID).First().Quantity = db.ShopCart.Where(x => x.UserName == User.Identity.Name && x.ProductID == shopCartProduct.ID).First().Quantity + shopCartProduct.Quantity;
                        }
                        else
                        {
                            db.ShopCart.Add(new ShopCarts() { ProductID = shopCartProduct.ID, Quantity = shopCartProduct.Quantity, UserName = User.Identity.Name });
                        }
                    }
                    db.SaveChanges();
                    return "{}"; //for ajax this means success
                }
                else throw (new Exception());
            }
            catch (Exception e)
            {
                logger.Error(e.ToString());
                return "Error";
            }
        }



        /// <summary>
        /// Deletes a product from the shopcart table in the database.
        /// </summary>
        /// <param name="id">The id of the product that is going to be deleted.</param>
        /// <returns>"{}" on success, "Error" on failure.</returns>
        public string Delete(int? id)
        {
            if (id != null && User.Identity.IsAuthenticated)
            {
                db.ShopCart.Remove(db.ShopCart.Where(x => x.UserName == User.Identity.Name && x.ProductID == id).First());
                db.SaveChanges();
                return "{}";
            }
            else
            {
                return "Error";
            }
        }


        /// <summary>
        /// Send back a JsonDataTableObject as json with all the information that we need to populate datatable
        /// </summary>
        /// <param name="draw">Draw order. Client send a draw id in request to keep track of asyncron response</param>
        /// <param name="start">Start from this item</param>
        /// <param name="length">Take a list with "lenght" (if exists) objects inside.</param>
        /// <returns>JsonDataTableObject</returns>
        public JsonResult JsonTableFill(int draw, int start, int length)
        {
            string json = Request.QueryString["json"] ?? "";



            const int TOTAL_ROWS = 999;



            //init list of products in shopcart
            IQueryable<ProductShopCartDetailed> list;
            if (User.Identity.IsAuthenticated)
            {
                list = from s in db.ShopCart
                       join p in db.Products on s.ProductID equals p.ProductID
                       join c in db.Categories on p.CategoryID equals c.CategoryID
                       where s.UserName == User.Identity.Name
                       select new ProductShopCartDetailed
                       {
                           Category = c.CategoryName,
                           ID = s.ProductID,
                           ProductName = p.ProductName,
                           Quantity = s.Quantity,
                           UnitPrice = p.UnitPrice ?? 999999
                       };
            }
            else
            {
                if (json != "")
                    list = JsonConvert.DeserializeObject<List<ProductShopCartDetailed>>(json).AsQueryable();
                else
                    list = new List<ProductShopCartDetailed>().AsQueryable();
            }


            int sortColumn = -1;
            string sortDirection = "asc";
            if (length == -1)
            {
                length = TOTAL_ROWS;
            }

            // note: we only sort one column at a time
            if (Request.QueryString["order[0][column]"] != null)
            {
                sortColumn = int.Parse(Request.QueryString["order[0][column]"]);
            }

            if (Request.QueryString["order[0][dir]"] != null)
            {
                sortDirection = Request.QueryString["order[0][dir]"];
            }

            //list of product that contain "search"

            //order list
            switch (sortColumn)
            {
                case -1: //sort by first column
                    goto FirstColumn;
                case 0: //first column
                    FirstColumn:
                    if (sortDirection == "asc")
                    {
                        list = list.OrderBy(x => x.ProductName);
                    }
                    else
                    {
                        list = list.OrderByDescending(x => x.ProductName);
                    }
                    break;
                case 1: //second column
                    if (sortDirection == "asc")
                    {

NorthwindWeb/Views/ShopCart/ConfirmOrder.cshtml
@{
    ViewBag.Title = "View";
}

<h2>Va rugam sa verificati daca informatiile de pe comanda sunt corecte.</h2>

NorthwindWeb/Views/ShopCart/CreateCustomers.cshtml
@model NorthwindWeb.ViewModels.Customer

@{
    ViewBag.Title = "Adauga";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/CustomerStyle.css" rel="stylesheet" />
<h2>Datele dumneavoastra nu sunt complete</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)
   

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Nume Companie</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Pozitie</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactTitle)
                @Html.ValidationMessageFor(model => model.ContactTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Adresa<span class = "text-danger">*</span></strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Oras</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Regiune</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region)
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Cod Postal</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode)
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Tara</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country)
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Telefon<span class="text-danger">*</span></strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Fax</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fax)
                @Html.ValidationMessageFor(model => model.Fax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adauga" class="btn btn-default" />
                @Html.ActionLink("Inapoi", "Index", "Home", new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}





@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

NorthwindWeb/Views/ShopCart/Index.cshtml
@model List<NorthwindWeb.Models.Shippers>
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container whiterounded coloronwhite">
    <h2>Cos de Cumparaturi</h2><hr />

    <table id="ShopCartTable" class="cell-border hover order-column coloronwhite">
        <thead>
            <tr>
                <th>
                    Nume Produs
                </th>
                <th>
                    Cantitate
                </th>
                <th>
                    Pret unitar
                </th>
                <th>
                    Pret total
                </th>
                <th>
                    Sterge
                </th>
            </tr>
        </thead>
        <tbody></tbody>

    </table>
    <br />
    <div class="container col-xs-9">
        <strong><span class="coloronwhite pull-right">Total comanda = <span id="totalComanda" class="coloronwhite"></span></span></strong>
    </div>

    @using (Html.BeginForm("GetShipVia", "ShopCart", FormMethod.Post, htmlAttributes: new { @class = "ord-form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form">
            <strong class="coloronwhite">Selecteaza Curierul</strong><br />
           
            @Html.DropDownList("ShipVia", (IEnumerable<SelectListItem>)ViewBag.ShipVia, htmlAttributes: new { @class = "form"})
           
            <br />
            <br />
            <input type="submit" value="Trimite Comanda" class="btn btn-default" />

        </div>
        <br />
                }
</div>