NorthwindWeb/Models/Shippers.cs
namespace NorthwindWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    /// <summary>
    /// The entity that contains information about shippers, located in database.
    /// </summary>
    public partial class Shippers
    {

        /// <summary>
        ///  Default constructor. Initialises new empty instances for Orders.
        /// </summary>
        public Shippers()
        {
            Orders = new HashSet<Orders>();
        }


        /// <summary>
        /// The ID through which we find the shipper.
        /// </summary>
        [Key]
        public int ShipperID { get; set; }

        /// <summary>
        /// The CompanyName through which we find the shipper.
        /// </summary>
        [Required]
        [StringLength(40)]
        public string CompanyName { get; set; }

        /// <summary>
        /// The Phone through which we find the shipper.
        /// </summary>
        [StringLength(24)]
        public string Phone { get; set; }


        /// <summary>
        /// The shipper which contains more orders.
        /// </summary>
        public virtual ICollection<Orders> Orders { get; set; }
    }
}

NorthwindWeb/Controllers/ShippersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NorthwindWeb.Models;
using NorthwindWeb.Models.Interfaces;
using NorthwindWeb.Models.ExceptionHandler;
using NorthwindWeb.Context;

namespace NorthwindWeb.Controllers
{

    /// <summary>
    /// Shippers Controller. For table Shippers
    /// </summary>
    [Authorize(Roles = "Admins, Managers")]
    public class ShippersController : Controller, IJsonTableFill
    {
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(HomeController));  //Declaring Log4Net to log errors in Event View-er in NorthwindLog Application log.
        private NorthwindDatabase db = new NorthwindDatabase();

        /// <summary>
        /// Displays a page with all the shippers existing in the database.
        /// </summary>
        /// <param name="search">The search look to find something asked</param>
        /// <returns>Shippers index view</returns>
        public async Task<ActionResult> Index(string search = "")
        {
            return View(await db.Shippers.Where(x => x.CompanyName.Contains(search)).ToListAsync());
        }

        /// <summary>
        /// Displays a page showing all the information about one shipper.
        /// </summary>
        /// <param name="id">The id of the shipper whose information to show</param>
        /// <returns>Shippers details view</returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //take details of Shipper
            Shippers shippers = await db.Shippers.FindAsync(id);
            if (shippers == null)
            {
                return HttpNotFound();
            }
            return View(shippers);
        }

        /// <summary>
        /// Returns the view containing the form neccesary for creating a new shipper.
        /// </summary>
        /// <returns>Create view.</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Inserts a shipper into the database table. If it fails, goes back to the form.
        /// </summary>
        /// <param name="shippers">The shipper entity to be inserted</param>
        /// <returns>If successful returns shippers index view, else goes back to form.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ShipperID,CompanyName,Phone")] Shippers shippers)
        {
            if (ModelState.IsValid)
            {
                db.Shippers.Add(shippers);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(shippers);
        }

        /// <summary>
        /// Returns the view containing the form necessary for editing an existing shipper.
        /// </summary>
        /// <param name="id">The id of the shipper that is going to be edited</param>
        /// <returns>Shippers edit view</returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //take details of Shipper
            Shippers shippers = await db.Shippers.FindAsync(id);
            if (shippers == null)
            {
                return HttpNotFound();
            }
            return View(shippers);
        }

        /// <summary>
        /// Updates the database changing the fields of the shipper whose id is equal to the id of the provided shippers parameter to those of the parameter.
        /// </summary>
        /// <param name="shippers">The changed shipper.</param>
        /// <returns>Shippers index view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ShipperID,CompanyName,Phone")] Shippers shippers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(shippers).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(shippers);
        }

        /// <summary>
        /// Displays a confirmation page for the following delete.
        /// </summary>
        /// <param name="id">The shipper that is going to be deleted.</param>
        /// <returns>Delete view</returns>
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //take details of Shipper
            Shippers shippers = await db.Shippers.FindAsync(id);
            if (shippers == null)
            {
                return HttpNotFound();
            }
            return View(shippers);
        }

        /// <summary>
        /// Deletes a shipper from the database. The shipper must not have id in employees.
        /// </summary>
        /// <param name="id">The id of the shipper that is going to be deleted</param>
        /// <returns>Shippers index view</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            //take details of Shipper
            Shippers shippers = await db.Shippers.FindAsync(id);
            
            try 
            {
                db.Shippers.Remove(shippers);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch(Exception exception)
            {
                logger.Error(exception.ToString());
                string list = "";
                var orderid = db.Orders.Include(x => x.Shipper).Where(x => x.ShipVia == id).Select(x => new { x.OrderID });
                foreach (var i in orderid)
                {   //lopp in all OrderID
                    list = list + i.OrderID.ToString() + ", ";
                }
                throw new DeleteException("Nu poti sterge expeditorul deoarece contine angajati cu id-urile:\n" + list + "\n Pentru a putea sterge acest expeditor trebuie sterse comenzile si detaliile lor.");
            }
        }

        /// <summary>
        /// Function used to control the dashboard datatables local
        /// </summary>
        /// <returns>A JSON filtered shipper list.</returns>
        public JsonResult JsonTableFill()
        {
            var shippers = db.Shippers.OrderBy(x => x.ShipperID);

            //Select what wee need in table
            return Json(
                shippers.Select(x => new NorthwindWeb.Models.ServerClientCommunication.ShipperData
                {
                    ID = x.ShipperID,
                    CompanyName = x.CompanyName,
                    Phone = x.Phone
                })
                , JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NorthwindWeb/Views/Shippers/Create.cshtml
@model NorthwindWeb.Models.Shippers

@{
    ViewBag.Title = "Adauga";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Adauga</h2>
<ol class="breadcrumb">
    <li>
        @Html.ActionLink("Dashboard", "Home", "Dashboard")
    </li>
    <li>
        @Html.ActionLink("Expeditori", "Index", "Shippers")
    </li>
    <li class="active">Adauga</li>
</ol>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expeditori</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Nume Companie</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Telefon</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Creaza" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NorthwindWeb/Views/Shippers/Delete.cshtml
@model NorthwindWeb.Models.Shippers

@{
    ViewBag.Title = "Sterge";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Sterge</h2>
<hr />
<ol class="breadcrumb">
    <li>
        @Html.ActionLink("Dashboard", "Home", "Dashboard")
    </li>
    <li>
        @Html.ActionLink("Expeditori", "Index", "Shippers")
    </li>
    <li class="active">Sterge</li>
</ol>
<h3>Esti sigur ca vrei sa-l stergi?</h3>
<div>
    
    <hr />
    <h4>Expeditor</h4>
    <dl class="dl-horizontal">
        <dt>
            Nume Companie
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)<br />
        </dd>

        <dt>
            Telefon
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)<br />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Inapoi", "Index", "Shippers", new { @class = "btn btn-default" })
            <input type="submit" value="Sterge" class="btn btn-default" />
            
        </div>
    }
</div>

NorthwindWeb/Views/Shippers/Details.cshtml
@model NorthwindWeb.Models.Shippers

@{
    ViewBag.Title = "Detalii";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Detalii</h2>
<hr />
<ol class="breadcrumb">
    <li>
        @Html.ActionLink("Dashboard", "Home", "Dashboard")
    </li>
    <li>
        @Html.ActionLink("Expeditori", "Index", "Shippers")
    </li>
    <li class="active">Detalii</li>
</ol>
<div>
    <h4>Expeditori</h4>
    <hr />
  
    <dl class="dl-horizontal">
        <dt>
            Nume Companie
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)<br />
        </dd>

        <dt>
            Telefon
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)<br />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Inapoi", "Index", null, new { @class = "btn btn-default" })
    @Html.ActionLink("Modifica", "Edit", new { id = Model.ShipperID } ,new { @class = "btn btn-default" })
</p>   

NorthwindWeb/Views/Shippers/Edit.cshtml
@model NorthwindWeb.Models.Shippers

@{
    ViewBag.Title = "Modifica";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Modifica</h2>
<hr />
<ol class="breadcrumb">
    <li>
        @Html.ActionLink("Dashboard", "Home", "Dashboard")
    </li>
    <li>
        @Html.ActionLink("Expeditori", "Index", "Shippers")
    </li>
    <li class="active">Modifica</li>
</ol>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expeditor</h4>
        <hr />
       
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ShipperID)

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Nume Companie</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2 bold"><strong>Telefon</strong></span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salveaza" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Inapoi", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NorthwindWeb/Views/Shippers/Index.cshtml
@model IEnumerable<NorthwindWeb.Models.Shippers>

@{
    ViewBag.Title = "Expeditori";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Expeditori</h2>
<hr />
<ol class="breadcrumb">
    <li>
        @Html.ActionLink("Dashboard", "Home", "Dashboard")
    </li>

    <li class="active">Expeditori</li>
</ol>
<hr />
<br />
<div>
    @Html.ActionLink("Adauga Expeditor", "Create", null, new { @class = "btn btn-default" })
    <br /><br />
</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    Expeditori
                </h4>
            </div>
            <div class="panel-body">
                <table id="ShippersTable" class="cell-border hover order-column">

                    <thead>
                        <tr>
                            <th>
                                Nume Companie
                            </th>
                            <th>
                                Telefon
                            </th>
                            <th>
                                Sterge
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>