NorthwindWeb/Controllers/TerritoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NorthwindWeb.Models;
using NorthwindWeb.Models.ExceptionHandler;
using NorthwindWeb.Context;

namespace NorthwindWeb.Controllers
{

    /// <summary>
    /// Territories Controller. For table Territories
    /// </summary>
    [Authorize(Roles = "Admins, Managers")]
    public class TerritoriesController : Controller
    {
        private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(HomeController));  //Declaring Log4Net to log errors in Event View-er in NorthwindLog Application log.
        private NorthwindDatabase db = new NorthwindDatabase();

        /// <summary>
        /// Displays a page showing all the information about one territory.
        /// </summary>
        /// <param name="id">The id of the territory whose information to show</param>
        /// <returns>Territory details view</returns>
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //take details of Territory
            Territories territories = await db.Territories.FindAsync(id);
            if (territories == null)
            {
                return HttpNotFound();
            }
            return View(territories);
        }

        /// <summary>
        /// Returns the view containing the form neccesary for creating a new territory.
        /// </summary>
        /// <returns>Create view.</returns>
        public ActionResult Create(int? id)
        {
            ViewBag.regionid = id;
            return View();
        }

        /// <summary>
        /// Inserts a territory into the database table. If it fails, goes back to the form.
        /// </summary>
        /// <param name="territories">The territory entity to be inserted</param>
        /// <param name="id">The territory find by region's id</param>
        /// <returns>If successful returns territories index view, else goes back to form.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "TerritoryDescription")] Territories territories, int id)
        {
            territories.RegionID = id;
            if (db.Territories.Any())
            {
                var lastItem = db.Territories.Select(x => new { nr = x.TerritoryID }).ToList().OrderByDescending(x => int.Parse(x.nr)).First();
                territories.TerritoryID = (int.Parse(lastItem.nr) + 1).ToString();
            }
            else
            {
                territories.TerritoryID = "1";
            }
            if (ModelState.IsValid)
            {
                db.Territories.Add(territories);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Regions", new { id = id });
            }
            ViewBag.regionid = id;
            return View(territories);
        }

        /// <summary>
        /// Returns the view containing the form necessary for editing an existing territory.
        /// </summary>
        /// <param name="id">The id of the territory that is going to be edited</param>
        /// <returns>Territories edit view</returns>
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //take details of Territory
            ViewBag.RegionsID = Convert.ToInt32(TempData["RegionID"]);
            TempData["RegionID"] = ViewBag.RegionsID;
            Territories territories = await db.Territories.FindAsync(id);
            if (territories == null)
            {
                return HttpNotFound();
            }
            ViewBag.RegionID = new SelectList(db.Regions, "RegionID", "RegionDescription", territories.RegionID);
            territories.TerritoryDescription = territories.TerritoryDescription.Trim();
            return View(territories);
        }

        /// <summary>
        /// Updates the database changing the fields of the territory whose id is equal to the id of the provided territories parameter to those of the parameter.
        /// </summary>
        /// <param name="territories">The changed territory.</param>
        /// <returns>Territories index view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "TerritoryID,TerritoryDescription,RegionID")] Territories territories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(territories).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction("Details", "Regions", new { id = Convert.ToInt32(TempData["RegionID"]) });
            }
            
            ViewBag.RegionID = new SelectList(db.Regions, "RegionID", "RegionDescription", territories.RegionID);
            return View(territories);
        }

        /// <summary>
        /// Displays a confirmation page for the following delete.
        /// </summary>
        /// <param name="id">The territory that is going to be deleted.</param>
        /// <returns>Delete view</returns>
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //take details of Territory
            Territories territories = await db.Territories.FindAsync(id);
            if (territories == null)
            {
                return HttpNotFound();
            }
            return View(territories);
        }

        /// <summary>
        /// Deletes a territory from the database. The territory must not have employees.
        /// </summary>
        /// <param name="id">The id of the territory that is going to be deleted</param>
        /// <returns>Territories index view</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            //take details of Territory
            Territories territories = await db.Territories.FindAsync(id);
            int idRegion = territories.RegionID;
            try
            {
                territories.Employees.Clear();
                db.Territories.Remove(territories);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Regions", new { id = idRegion });
            }
            catch (Exception exception)
            {
                logger.Error(exception.ToString());
                throw new DeleteException("Nu puteti sterge teritoriul deoarece are angajati asignati la el. \nPentru a putea sterge acest teritoriu trebuie sa stergi angajatii asignati mai intai!.");
            }


        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NorthwindWeb/Views/Territories/Create.cshtml
@model NorthwindWeb.Models.Territories

@{
    ViewBag.Title = "Adauga";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

    <h2>Adauga</h2>
    <hr />
    <ol class="breadcrumb">
        <li>
            @Html.ActionLink("Dashboard", "Home", "Dashboard")
        </li>
        <li>
            @Html.ActionLink("Regiuni", "Index", "Regions")
        </li>
        <li>
            @Html.ActionLink("Detalii","Details","Regions", new { id = ViewBag.regionid }, null)
        </li>
        <li class="active">Adauga</li>
    </ol>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Territorii</h4>
            <hr />
            @Html.ValidationSummary(true)
            <div class="form-group">
                @*@Html.LabelFor(model => model.TerritoryDescription, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <span class="control-label col-md-2 bold"><strong>Denumire Teritoriu</strong></span>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TerritoryDescription)
                    @Html.ValidationMessageFor(model => model.TerritoryDescription)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adauga" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Inapoi", "Details", "Regions", new { id = ViewBag.regionid }, new { @class = "btn btn-default" })
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NorthwindWeb/Views/Territories/Delete.cshtml
@model NorthwindWeb.Models.Territories

@{
    ViewBag.Title = "Sterge";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

    <h2>Sterge</h2>
    <hr />
    <ol class="breadcrumb">
        <li>
            @Html.ActionLink("Dashboard", "Home", "Dashboard")
        </li>
        <li>
            @Html.ActionLink("Regiuni", "Index", "Regions")
        </li>
        <li>
            @Html.ActionLink("Detalii", "Details", "Regions", new { id = Model.RegionID }, null)
        </li>
        <li class="active">Sterge</li>
    </ol>

    <h3>Sigur vrei sa stergi?</h3>
    <div>
        <h4>Teritorii</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Descriere regiune<br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Region.RegionDescription)<br />
            </dd>

            <dt>
               Descriere teritoriu<br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TerritoryDescription)<br />
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                @Html.ActionLink("Inapoi", "Details", "Regions", new { id = Model.RegionID }, new { @class = "btn btn-default" })
                <input type="submit" value="Sterge" class="btn btn-default" />
            </div>
        }
    </div>

NorthwindWeb/Views/Territories/Details.cshtml
@model NorthwindWeb.Models.Territories

@{
    ViewBag.Title = "Detalii";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}


    <h2>Detalii</h2>
    <hr />
    <ol class="breadcrumb">
        <li>
            @Html.ActionLink("Dashboard", "Home", "Dashboard")
        </li>
        <li>
            @Html.ActionLink("Regiuni", "Index", "Regions")
        </li>
        <li>
            @Html.ActionLink("Detalii", "Details", "Regions")
        </li>
        <li class="active">Detalii</li>
    </ol>

    <div>
        <h4>Teritorii</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Region.RegionDescription)<br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Region.RegionDescription)<br />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TerritoryDescription)<br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TerritoryDescription)<br />
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Inapoi", "Index", "Territories", new { @class = "btn btn-default" })
        @Html.ActionLink("Modifica", "Edit", new { id = Model.TerritoryID }, new { @class = "btn btn-default" })
    </p>

NorthwindWeb/Views/Territories/Edit.cshtml
@model NorthwindWeb.Models.Territories

@{
    ViewBag.Title = "Modifica";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

    <h2>Modifica</h2>
    <hr />
    <ol class="breadcrumb">
        <li>
            @Html.ActionLink("Dashboard", "Home", "Dashboard")
        </li>
        <li>
            @Html.ActionLink("Regiuni", "Index", "Regions")
        </li>
        <li>
            @Html.ActionLink("Detalii", "Details", "Regions", new { id = Model.RegionID }, null)
        </li>
        <li class="active">Modifica</li>
    </ol>


    @using (Html.BeginForm(new { TerritoryID = Model.TerritoryID }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Teritorii</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.RegionID,"ID Regiune", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RegionID)
                    @Html.ValidationMessageFor(model => model.RegionID)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TerritoryDescription,"Descriere Teritoriu", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TerritoryDescription)
                    @Html.ValidationMessageFor(model => model.TerritoryDescription)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salveaza" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Inapoi", "Details", "Regions", new { id = Model.RegionID}, new { @class = "btn btn-default" })
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}